name: standalone3d

services:
  frontend:
    build:
      context: .
      dockerfile: frontend-Dockerfile
    volumes:
      - /opt/standalone/web:/cslt/web
  backend:
    ports:
      - "$BACKEND_PORT:$BACKEND_PORT"
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./logs/:/cslt/backend/logs
      - /opt/standalone/web:/cslt/web
