name: standalone3d

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "$HTTP_PORT:$HTTP_PORT"
      - "$HTTPS_PORT:$HTTPS_PORT"
      - "$ADMIN_PORT:$ADMIN_PORT"
    volumes:
      - ./logs:/cslt/logs
      - $CERTS_DIR:/certs
  frontend:
    build:
      context: .
      dockerfile: frontend-Dockerfile
    volumes:
      - /opt/standalone/web:/cslt/web
  backend:
    ports:
      - "$BACKEND_PORT:$BACKEND_PORT"
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./logs/:/cslt/backend/logs
      - /opt/standalone/web:/cslt/web
