name: standalone3d

services:
  server:
    environment:
      - BACKEND_PORT
      - CERTS_DIR
      - DOMAIN_NAME
      - ROOT_DIR_3D
      - TLS_CERT_LOC
      - TLS_KEY_LOC
    image: docker.compusult.com:5000/standalone3d-server:$IMAGE_TAG
    ports:
      - "$HTTP_PORT:$HTTP_PORT"
      - "$HTTPS_PORT:$HTTPS_PORT"
      - "$ADMIN_PORT:$ADMIN_PORT"
    volumes:
      - docker_web:/srv
      - ./logs/:/cslt/logs
      - $CERTS_DIR:/certs
  frontend:
    image: docker.compusult.com:5000/standalone3d-frontend:$IMAGE_TAG
    volumes:
      - docker_web:/cslt/web
  backend:
    environment:
      - BACKEND_PORT
    image: docker.compusult.com:5000/standalone3d-backend:$IMAGE_TAG
    ports:
      - "$BACKEND_PORT:$BACKEND_PORT"
    volumes:
      - ./logs/:/cslt/backend/logs
      - docker_web:/cslt/web
volumes: 
  docker_web:
    driver: local
