# syntax=docker/dockerfile:1

FROM ghcr.io/osgeo/gdal:alpine-small-3.8.4
COPY --from=golang:1.21 /usr/local/go /usr/local/go
ENV PATH="/usr/local/go/bin:${PATH}"
WORKDIR /cslt
RUN [ "mkdir", "-p", "./backend" ]
#COPY ./go.mod ./backend/go.mod
#COPY ./go.sum ./backend/go.sum
COPY . ./backend
WORKDIR /cslt/backend
#RUN [ "go", "mod", "download" ]
RUN [ "apk", "add", "gcc", "musl-dev" ]
RUN [ "go", "build" ]
#RUN [ "rm", "-rf", "go.mod", "go.sum" ]
#RUN [ "rm", "-rf", "Backend.go", "CMakeLists.txt", "Database.go", "DirList.go", "Err.go", "FileUpload.go", "HandleAddWebsocket.go", "HandleDelete.go", "HandleFeatures.go", "HandleGet.go", "HandleHead.go", "HandleKml.go", "HandleNewClient.go", "HandlePatch.go", "HandlePost.go", "HandlePut.go", "HandleShape.go", "HandleUnknownRequest.go", "RequestQueue.go", "build", "compile_commands.json", "Logging.go", "shape2json.c", "shape2json.h","go.mod", "go.sum", "Dockerfile", "cslt3d", "Dockerfile_base", ]
WORKDIR /cslt
RUN [ "rm", "-rf", "backend" ]
RUN [ "mkdir", "backend" ]
