pipeline {
    agent any
    environment {
        BACKEND_PORT = '8080'
        CERTS_DIR = '/etc/httpd/conf/site_certs'
        HTTP_PORT = '2015'
        HTTPS_PORT = '443'
        ADMIN_PORT = '2019'
        DOMAIN_NAME = '3d-dev.compusult.com'
        ROOT_DIR_3D = '/opt/standalone'
        TLS_CERT_LOC = 'compusult_com_2024.crt'
        TLS_KEY_LOC = 'compusult_com_2048_nopass.key'
        CADDYFILE = 'caddyfile'
        CGO_CFLAGS="-I/usr/include/gdal"
    }
    tools {
        go 'Go1.22.0'
    }
    stages {
        stage ('Checkout') {
            steps {
                echo "Checkout"
            }
        }
        stage('Build') {
            steps {
                echo "Building on ${NODE_NAME}..."
                sh 'npm install'
                sh 'npm run full-build-release'
                }
            }
        stage('Containerize') {
            steps {
                    echo "Building Docker image on ${NODE_NAME}..."
                    sh 'docker compose build'
                }
        }
        stage('Test') {
            steps {
                echo "Testing on ${NODE_NAME}..."
                dir('test'){
                    sh 'npx jest'
                }
            }
        }
    stage('Cleanup') {
            steps {
                echo 'Cleaning up...'
                catchError {
                    sh 'docker rm -vf $(docker ps -qa --filter "ancestor=standalone3d-frontend")'
                    sh 'docker rm -vf $(docker ps -qa --filter "ancestor=standalone3d-backend")'
                    sh 'docker rm -vf $(docker ps -qa --filter "ancestor=standalone3d-server")'
                }
            }
        }
    }
    
    post {
        success {
            gerritReview labels: ["Verification": +1], message: 'Automated Verification Passed.'
            cleanWs()
        }
        failure {
            gerritReview labels: ["Verification": -1], message: "Automated Verification Failed. See ${BUILD_URL} for full build log."
        }
    }
}
