pipeline {
    agent any
    tools {
        go 'Go1.22.0'
    }
    stages {
        stage ('Checkout') {
            steps {
                echo "Checkout"
            }
        }
        stage('Build') {
            steps {
                echo "Building on ${NODE_NAME}..."
                sh 'npm install'
                sh 'npm run full-build-release'
                }
            }
        stage('Test') {
            steps {
                echo "Testing on ${NODE_NAME}..."
                dir('test'){
                    sh 'npx jest'
                }
            }
        }
        stage('Containerize') {
            steps {
                echo "Building Docker image on ${NODE_NAME}..."
                sh 'sudo docker build -t cslt3d .'
            }
        }
    }
    
    post {
        success {
            gerritReview labels: ["Verification": +1], message: 'Automated Verification Passed.'
            cleanWs()
        }
        failure {
            gerritReview labels: ["Verification": -1], message: "Automated Verification Failed. See ${BUILD_URL} for full build log."
        }
    }
}
